### ISSUE TITLE
tokubatch.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#540] opened 2020-03-25 13:57 UTC
**Jenis iklan** (hapus yang tidak perlu)
- 3p safelink

**Sample URL**
https://www.tokubatch.com/ultraman-x-episode-1-22-tamat-sub-indo-batch/
https://www.tokubatch.com/kamen-rider-zi-o-2019/

**Penjelasan Lebih Lanjut**
`https://pastebin.com/raw/Rw38SyHy
`

**Comment by realodix** [comment] 2020-03-26 11:31
Duplicate of #234

**Closed by realodix** 2020-03-26 11:31 UTC
