### ISSUE TITLE
lk21official.wiki

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1665] opened 2023-12-31 08:13 UTC
### Sample URL

https://tv7.lk21official.wiki/luck-key-2016/

### Ad Blocker

uBlock Origin

### Keterangan

![image](https://github.com/realodix/AdBlockID/assets/19517680/3c2ef034-175c-4b70-b28d-475896fb6dac)

**Comment by realodix** [comment] 2023-12-31 20:37
Duplicate of #1662

Sudah ditangani

**Closed by realodix** 2023-12-31 20:37 UTC
Labels: C: Native
