### ISSUE TITLE
OppaDrama (185.217.95.30) - (Bug on AdGuard)

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1580] opened 2023-10-13 06:52 UTC
![Screenshot_2023-10-13-13-49-08-36_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/67d11d49-8160-48ff-a721-a062c30e635f)

Tanda silang hilang di ublock origin tapi
Bug untuk adguard

**Comment by Jokopentil** [comment] 2023-10-13 06:52
http://185.217.95.30/the-glory-episode-16-end/

**Comment by realodix** [comment] 2023-10-13 08:29
Duplicate of #1576

**Closed** 2023-10-13 08:29 UTC
Labels: R: Duplicate, C: Pop-up ads
