### ISSUE TITLE
animeindo.to

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#210] opened 2020-01-06 12:52 UTC
**Jenis iklan** (hapus yang tidak perlu)
- Pop-up

**Sample URL**
https://animeindo.to/

**Penjelasan Lebih Lanjut**
Popups

**Comment by realodix** [comment] 2020-01-06 16:22
Ping @okiehsch @AdamWr

**Comment by AdamWr** [comment] 2020-01-06 19:58
It seems that it's already fixed in AdGuard Base filter, because I can't reproduce it.
https://github.com/AdguardTeam/AdguardFilters/commit/b5e04675552ee67acfd2bc286ac96321fa182544

**Comment by okiehsch** [comment] 2020-01-07 00:05
Fixed.

**Closed** 2020-01-07 00:18 UTC
Labels: A: Pop-up ads
