### ISSUE TITLE
nekopoi.care

### ISSUE THREAD

**Issue by SuperMarioMakerII** [realodix/AdBlockID#613] opened 2020-09-04 17:20 UTC
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
nekopoi.care

**Penjelasan Lebih Lanjut**
baner

**Comment by realodix** [comment] 2020-09-04 19:25
Duplicate of #83

**Closed by realodix** 2020-09-04 19:25 UTC
Labels: duplicate, nsfw

**Comment by Recehan-Slayer** [comment] 2021-03-30 05:23
@realodix banner judi gan di versi mobilenya

**Comment by Recehan-Slayer** [comment] 2021-03-30 15:45
masi ada bro 


![Uploading Screenshot_2021-03-30-22-43-04-634_com.kiwibrowser.browser.jpg…]()

**Comment by realodix** [comment] 2021-03-30 19:02
> masi ada bro
> 
> Uploading Screenshot_2021-03-30-22-43-04-634_com.kiwibrowser.browser.jpg…

Gak bisa diklik

**Comment by Recehan-Slayer** [comment] 2021-03-31 07:49
![Screenshot_2021-03-31-14-47-25-809_com kiwibrowser browser](https://user-images.githubusercontent.com/9379770/113109322-686e3480-91f5-11eb-824b-88b84520ef24.jpg)
