### ISSUE TITLE
sektekomik.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#905] opened 2021-05-21 01:58 UTC
**Jenis iklan**
- Banner

**Sample URL**
https://sektekomik.com/manga/rebirth-of-the-urban-immortal-cultivator/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment] 2021-05-21 04:07
Duplicate of #419, #786, #804

---

Thank you

**Closed by realodix** 2021-05-21 04:07 UTC
Labels: C: Native

**Comment by Recehan-Slayer** [comment] 2021-06-07 17:25
@realodix gan gmbarnya kok tidak keluar ya
https://sektekomik.com/cultivation-return-on-campus-chapter-222-bahasa-indonesia/

**Comment by Recehan-Slayer** [comment] 2021-06-09 05:25
@realodix  gan punya gw kok thumbnailnya ga muncul ya.  klo gambarnya uda fix
<details>

![Untitled](https://user-images.githubusercontent.com/9379770/121298199-ac7c6480-c91d-11eb-9cbd-8469fbdbb477.jpg)

**Comment by realodix** [comment] 2021-08-30 12:38
Kurang tahu deh. Di Saya muncul, gak ada masalah.

<details>
  <summary>Screenshot</summary>
  
  ![noname](https://user-images.githubusercontent.com/1314456/131340050-2737e0f8-b3f4-42a7-ae8f-304a6031e004.png)
</details>
