### ISSUE TITLE
mangakita.net

### ISSUE THREAD

**Issue by GrennKren** [realodix/AdBlockID#611] opened 2020-08-28 06:40 UTC
**Jenis iklan**
- Banner
- Lainnya

**Sample URL**
http://mangakita.net/

**Penjelasan Lebih Lanjut**
![Untitled](https://user-images.githubusercontent.com/34759917/91529683-4ac5ad80-e93c-11ea-9972-078560bc5739.jpg)

**Comment by realodix** [comment] 2020-09-01 13:11
Duplicate of #610

**Closed by realodix** 2020-09-01 13:11 UTC
Labels: A: Placeholders, A: Pop-up ads
